insert into banco (numero, nome) values ('001', 'BANCO DO BRASIL S.A (BB)');
insert into banco (numero, nome) values ('237', 'BRADESCO S.A');
insert into banco (numero, nome) values ('335', 'Banco Digio S.A');
insert into banco (numero, nome) values ('260', 'NU PAGAMENTOS S.A (NUBANK)');
insert into banco (numero, nome) values ('290', 'Pagseguro Internet S.A');
insert into banco (numero, nome) values ('323', 'Mercado Pago – conta do Mercado Livre');
insert into banco (numero, nome) values ('237', 'NEXT BANK (UTILIZAR O MESMO CÓDIGO DO BRADESCO)');
insert into banco (numero, nome) values ('637', 'BANCO SOFISA S.A (SOFISA DIRETO)');
insert into banco (numero, nome) values ('077', 'BANCO INTER S.A');
insert into banco (numero, nome) values ('341', 'ITAÚ UNIBANCO S.A');
insert into banco (numero, nome) values ('104', 'CAIXA ECONÔMICA FEDERAL (CEF)');
insert into banco (numero, nome) values ('033', 'BANCO SANTANDER BRASIL S.A');
insert into banco (numero, nome) values ('212', 'BANCO ORIGINAL S.A');
insert into banco (numero, nome) values ('756', 'BANCOOB (BANCO COOPERATIVO DO BRASIL)');
insert into banco (numero, nome) values ('655', 'BANCO VOTORANTIM S.A');
insert into banco (numero, nome) values ('655', 'NEON PAGAMENTOS S.A (OS MESMOS DADOS DO BANCO VOTORANTIM)');
insert into banco (numero, nome) values ('041', 'BANRISUL – BANCO DO ESTADO DO RIO GRANDE DO SUL S.A');
insert into banco (numero, nome) values ('389', 'BANCO MERCANTIL DO BRASIL S.A');
insert into banco (numero, nome) values ('422', 'BANCO SAFRA S.A');
insert into banco (numero, nome) values ('070', 'BANCO DE BRASÍLIA (BRB)');
insert into banco (numero, nome) values ('136', 'UNICRED COOPERATIVA');
insert into banco (numero, nome) values ('741', 'BANCO RIBEIRÃO PRETO');
insert into banco (numero, nome) values ('739', 'BANCO CETELEM S.A');
insert into banco (numero, nome) values ('743', 'BANCO SEMEAR S.A');
insert into banco (numero, nome) values ('100', 'PLANNER CORRETORA DE VALORES S.A');
insert into banco (numero, nome) values ('096', 'BANCO B3 S.A');
insert into banco (numero, nome) values ('747', 'Banco RABOBANK INTERNACIONAL DO BRASIL S.A');
insert into banco (numero, nome) values ('748', 'SICREDI S.A');
insert into banco (numero, nome) values ('752', 'BNP PARIBAS BRASIL S.A');
insert into banco (numero, nome) values ('091', 'UNICRED CENTRAL RS');
insert into banco (numero, nome) values ('399', 'KIRTON BANK');
insert into banco (numero, nome) values ('108', 'PORTOCRED S.A');
insert into banco (numero, nome) values ('757', 'BANCO KEB HANA DO BRASIL S.A');
insert into banco (numero, nome) values ('102', 'XP INVESTIMENTOS S.A');
insert into banco (numero, nome) values ('348', 'BANCO XP S/A');
insert into banco (numero, nome) values ('340', 'SUPER PAGAMENTOS S/A (SUPERDITAL)');
insert into banco (numero, nome) values ('364', 'GERENCIANET PAGAMENTOS DO BRASIL');
insert into banco (numero, nome) values ('084', 'UNIPRIME NORTE DO PARANÁ');
insert into banco (numero, nome) values ('180', 'CM CAPITAL MARKETS CCTVM LTDA');
insert into banco (numero, nome) values ('066', 'BANCO MORGAN STANLEY S.A');
insert into banco (numero, nome) values ('015', 'UBS BRASIL CCTVM S.A');
insert into banco (numero, nome) values ('143', 'TREVISO CC S.A');
insert into banco (numero, nome) values ('062', 'HIPERCARD BM S.A');
insert into banco (numero, nome) values ('074', 'BCO. J.SAFRA S.A');
insert into banco (numero, nome) values ('099', 'UNIPRIME CENTRAL CCC LTDA');
insert into banco (numero, nome) values ('025', 'BANCO ALFA S.A.');
insert into banco (numero, nome) values ('075', 'BCO ABN AMRO S.A');
insert into banco (numero, nome) values ('040', 'BANCO CARGILL S.A');
insert into banco (numero, nome) values ('190', 'SERVICOOP');
insert into banco (numero, nome) values ('063', 'BANCO BRADESCARD');
insert into banco (numero, nome) values ('191', 'NOVA FUTURA CTVM LTDA');
insert into banco (numero, nome) values ('064', 'GOLDMAN SACHS DO BRASIL BM S.A');
insert into banco (numero, nome) values ('097', 'CCC NOROESTE BRASILEIRO LTDA');
insert into banco (numero, nome) values ('016', 'CCM DESP TRÂNS SC E RS');
insert into banco (numero, nome) values ('012', 'BANCO INBURSA');
insert into banco (numero, nome) values ('003', 'BANCO DA AMAZONIA S.A');
insert into banco (numero, nome) values ('060', 'CONFIDENCE CC S.A');
insert into banco (numero, nome) values ('037', 'BANCO DO ESTADO DO PARÁ S.A');
insert into banco (numero, nome) values ('159', 'CASA CREDITO S.A');
insert into banco (numero, nome) values ('172', 'ALBATROSS CCV S.A');
insert into banco (numero, nome) values ('085', 'COOP CENTRAL AILOS');
insert into banco (numero, nome) values ('114', 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO');
insert into banco (numero, nome) values ('036', 'BANCO BBI S.A');
insert into banco (numero, nome) values ('394', 'BANCO BRADESCO FINANCIAMENTOS S.A');
insert into banco (numero, nome) values ('004', 'BANCO DO NORDESTE DO BRASIL S.A.');
insert into banco (numero, nome) values ('320', 'BANCO CCB BRASIL S.A');
insert into banco (numero, nome) values ('189', 'HS FINANCEIRA');
insert into banco (numero, nome) values ('105', 'LECCA CFI S.A');
insert into banco (numero, nome) values ('076', 'BANCO KDB BRASIL S.A.');
insert into banco (numero, nome) values ('082', 'BANCO TOPÁZIO S.A');
insert into banco (numero, nome) values ('286', 'CCR DE OURO');
insert into banco (numero, nome) values ('093', 'PÓLOCRED SCMEPP LTDA');
insert into banco (numero, nome) values ('273', 'CCR DE SÃO MIGUEL DO OESTE');
insert into banco (numero, nome) values ('157', 'ICAP DO BRASIL CTVM LTDA');
insert into banco (numero, nome) values ('183', 'SOCRED S.A');
insert into banco (numero, nome) values ('014', 'NATIXIS BRASIL S.A');
insert into banco (numero, nome) values ('130', 'CARUANA SCFI');
insert into banco (numero, nome) values ('127', 'CODEPE CVC S.A');
insert into banco (numero, nome) values ('079', 'BANCO ORIGINAL DO AGRONEGÓCIO S.A');
insert into banco (numero, nome) values ('081', 'BBN BANCO BRASILEIRO DE NEGOCIOS S.A');
insert into banco (numero, nome) values ('118', 'STANDARD CHARTERED BI S.A');
insert into banco (numero, nome) values ('133', 'CRESOL CONFEDERAÇÃO');
insert into banco (numero, nome) values ('121', 'BANCO AGIBANK S.A');
insert into banco (numero, nome) values ('083', 'BANCO DA CHINA BRASIL S.A');
insert into banco (numero, nome) values ('138', 'GET MONEY CC LTDA');
insert into banco (numero, nome) values ('024', 'BCO BANDEPE S.A');
insert into banco (numero, nome) values ('095', 'BANCO CONFIDENCE DE CÂMBIO S.A');
insert into banco (numero, nome) values ('094', 'BANCO FINAXIS');
insert into banco (numero, nome) values ('276', 'SENFF S.A');
insert into banco (numero, nome) values ('137', 'MULTIMONEY CC LTDA');
insert into banco (numero, nome) values ('092', 'BRK S.A');
insert into banco (numero, nome) values ('047', 'BANCO BCO DO ESTADO DE SERGIPE S.A');
insert into banco (numero, nome) values ('144', 'BEXS BANCO DE CAMBIO S.A.');
insert into banco (numero, nome) values ('126', 'BR PARTNERS BI');
insert into banco (numero, nome) values ('301', 'BPP INSTITUIÇÃO DE PAGAMENTOS S.A');
insert into banco (numero, nome) values ('173', 'BRL TRUST DTVM SA');
insert into banco (numero, nome) values ('119', 'BANCO WESTERN UNION');
insert into banco (numero, nome) values ('254', 'PARANA BANCO S.A');
insert into banco (numero, nome) values ('268', 'BARIGUI CH');
insert into banco (numero, nome) values ('107', 'BANCO BOCOM BBM S.A');
insert into banco (numero, nome) values ('412', 'BANCO CAPITAL S.A');
insert into banco (numero, nome) values ('124', 'BANCO WOORI BANK DO BRASIL S.A');
insert into banco (numero, nome) values ('149', 'FACTA S.A. CFI');
insert into banco (numero, nome) values ('197', 'STONE PAGAMENTOS S.A');
insert into banco (numero, nome) values ('142', 'BROKER BRASIL CC LTDA');
insert into banco (numero, nome) values ('389', 'BANCO MERCANTIL DO BRASIL S.A.');
insert into banco (numero, nome) values ('184', 'BANCO ITAÚ BBA S.A');
insert into banco (numero, nome) values ('634', 'BANCO TRIANGULO S.A (BANCO TRIÂNGULO)');
insert into banco (numero, nome) values ('545', 'SENSO CCVM S.A');
insert into banco (numero, nome) values ('132', 'ICBC DO BRASIL BM S.A');
insert into banco (numero, nome) values ('298', 'VIPS CC LTDA');
insert into banco (numero, nome) values ('129', 'UBS BRASIL BI S.A');
insert into banco (numero, nome) values ('128', 'MS BANK S.A BANCO DE CÂMBIO');
insert into banco (numero, nome) values ('194', 'PARMETAL DTVM LTDA');
insert into banco (numero, nome) values ('310', 'VORTX DTVM LTDA');
insert into banco (numero, nome) values ('163', 'COMMERZBANK BRASIL S.A BANCO MÚLTIPLO');
insert into banco (numero, nome) values ('280', 'AVISTA S.A');
insert into banco (numero, nome) values ('146', 'GUITTA CC LTDA');
insert into banco (numero, nome) values ('279', 'CCR DE PRIMAVERA DO LESTE');
insert into banco (numero, nome) values ('182', 'DACASA FINANCEIRA S/A');
insert into banco (numero, nome) values ('278', 'GENIAL INVESTIMENTOS CVM S.A');
insert into banco (numero, nome) values ('271', 'IB CCTVM LTDA');
insert into banco (numero, nome) values ('021', 'BANCO BANESTES S.A');
insert into banco (numero, nome) values ('246', 'BANCO ABC BRASIL S.A');
insert into banco (numero, nome) values ('751', 'SCOTIABANK BRASIL');
insert into banco (numero, nome) values ('208', 'BANCO BTG PACTUAL S.A');
insert into banco (numero, nome) values ('746', 'BANCO MODAL S.A');
insert into banco (numero, nome) values ('241', 'BANCO CLASSICO S.A');
insert into banco (numero, nome) values ('612', 'BANCO GUANABARA S.A');
insert into banco (numero, nome) values ('604', 'BANCO INDUSTRIAL DO BRASIL S.A');
insert into banco (numero, nome) values ('505', 'BANCO CREDIT SUISSE (BRL) S.A');
insert into banco (numero, nome) values ('196', 'BANCO FAIR CC S.A');
insert into banco (numero, nome) values ('300', 'BANCO LA NACION ARGENTINA');
insert into banco (numero, nome) values ('477', 'CITIBANK N.A');
insert into banco (numero, nome) values ('266', 'BANCO CEDULA S.A');
insert into banco (numero, nome) values ('122', 'BANCO BRADESCO BERJ S.A');
insert into banco (numero, nome) values ('376', 'BANCO J.P. MORGAN S.A');
insert into banco (numero, nome) values ('473', 'BANCO CAIXA GERAL BRASIL S.A');
insert into banco (numero, nome) values ('745', 'BANCO CITIBANK S.A');
insert into banco (numero, nome) values ('120', 'BANCO RODOBENS S.A');
insert into banco (numero, nome) values ('265', 'BANCO FATOR S.A');
insert into banco (numero, nome) values ('007', 'BNDES (Banco Nacional do Desenvolvimento Social)');
insert into banco (numero, nome) values ('188', 'ATIVA S.A INVESTIMENTOS');
insert into banco (numero, nome) values ('134', 'BGC LIQUIDEZ DTVM LTDA');
insert into banco (numero, nome) values ('641', 'BANCO ALVORADA S.A');
insert into banco (numero, nome) values ('029', 'BANCO ITAÚ CONSIGNADO S.A');
insert into banco (numero, nome) values ('243', 'BANCO MÁXIMA S.A');
insert into banco (numero, nome) values ('078', 'HAITONG BI DO BRASIL S.A');
insert into banco (numero, nome) values ('111', 'BANCO OLIVEIRA TRUST DTVM S.A');
insert into banco (numero, nome) values ('017', 'BNY MELLON BANCO S.A');
insert into banco (numero, nome) values ('174', 'PERNAMBUCANAS FINANC S.A');
insert into banco (numero, nome) values ('495', 'LA PROVINCIA BUENOS AIRES BANCO');
insert into banco (numero, nome) values ('125', 'BRASIL PLURAL S.A BANCO');
insert into banco (numero, nome) values ('488', 'JPMORGAN CHASE BANK');
insert into banco (numero, nome) values ('065', 'BANCO ANDBANK S.A');
insert into banco (numero, nome) values ('492', 'ING BANK N.V');
insert into banco (numero, nome) values ('250', 'BANCO BCV');
insert into banco (numero, nome) values ('145', 'LEVYCAM CCV LTDA');
insert into banco (numero, nome) values ('494', 'BANCO REP ORIENTAL URUGUAY');
insert into banco (numero, nome) values ('253', 'BEXS CC S.A');
insert into banco (numero, nome) values ('269', 'HSBC BANCO DE INVESTIMENTO');
insert into banco (numero, nome) values ('213', 'BCO ARBI S.A');
insert into banco (numero, nome) values ('139', 'INTESA SANPAOLO BRASIL S.A');
insert into banco (numero, nome) values ('018', 'BANCO TRICURY S.A');
insert into banco (numero, nome) values ('630', 'BANCO INTERCAP S.A');
insert into banco (numero, nome) values ('224', 'BANCO FIBRA S.A');
insert into banco (numero, nome) values ('600', 'BANCO LUSO BRASILEIRO S.A');
insert into banco (numero, nome) values ('623', 'BANCO PAN');
insert into banco (numero, nome) values ('204', 'BANCO BRADESCO CARTOES S.A');
insert into banco (numero, nome) values ('479', 'BANCO ITAUBANK S.A');
insert into banco (numero, nome) values ('456', 'BANCO MUFG BRASIL S.A');
insert into banco (numero, nome) values ('464', 'BANCO SUMITOMO MITSUI BRASIL S.A');
insert into banco (numero, nome) values ('613', 'OMNI BANCO S.A');
insert into banco (numero, nome) values ('652', 'ITAÚ UNIBANCO HOLDING BM S.A');
insert into banco (numero, nome) values ('653', 'BANCO INDUSVAL S.A');
insert into banco (numero, nome) values ('069', 'BANCO CREFISA S.A');
insert into banco (numero, nome) values ('370', 'BANCO MIZUHO S.A');
insert into banco (numero, nome) values ('249', 'BANCO INVESTCRED UNIBANCO S.A');
insert into banco (numero, nome) values ('318', 'BANCO BMG S.A');
insert into banco (numero, nome) values ('626', 'BANCO FICSA S.A');
insert into banco (numero, nome) values ('270', 'SAGITUR CC LTDA');
insert into banco (numero, nome) values ('366', 'BANCO SOCIETE GENERALE BRASIL');
insert into banco (numero, nome) values ('113', 'MAGLIANO S.A');
insert into banco (numero, nome) values ('131', 'TULLETT PREBON BRASIL CVC LTDA');
insert into banco (numero, nome) values ('011', 'C.SUISSE HEDGING-GRIFFO CV S.A (Credit Suisse)');
insert into banco (numero, nome) values ('611', 'BANCO PAULISTA');
insert into banco (numero, nome) values ('755', 'BOFA MERRILL LYNCH BM S.A');
insert into banco (numero, nome) values ('089', 'CCR REG MOGIANA');
insert into banco (numero, nome) values ('643', 'BANCO PINE S.A');
insert into banco (numero, nome) values ('140', 'EASYNVEST – TÍTULO CV S.A');
insert into banco (numero, nome) values ('707', 'BANCO DAYCOVAL S.A');
insert into banco (numero, nome) values ('288', 'CAROL DTVM LTDA');
insert into banco (numero, nome) values ('101', 'RENASCENCA DTVM LTDA');
insert into banco (numero, nome) values ('487', 'DEUTSCHE BANK S.A BANCO ALEMÃO');
insert into banco (numero, nome) values ('233', 'BANCO CIFRA');
insert into banco (numero, nome) values ('177', 'GUIDE');
insert into banco (numero, nome) values ('633', 'BANCO RENDIMENTO S.A');
insert into banco (numero, nome) values ('218', 'BANCO BS2 S.A');
insert into banco (numero, nome) values ('292', 'BS2 DISTRIBUIDORA DE TÍTULOS E INVESTIMENTOS');
insert into banco (numero, nome) values ('169', 'BANCO OLÉ BONSUCESSO CONSIGNADO S.A');
insert into banco (numero, nome) values ('293', 'LASTRO RDV DTVM LTDA');
insert into banco (numero, nome) values ('285', 'FRENTE CC LTDA');
insert into banco (numero, nome) values ('080', 'B&T CC LTDA');
insert into banco (numero, nome) values ('753', 'NOVO BANCO CONTINENTAL S.A BM');
insert into banco (numero, nome) values ('222', 'BANCO CRÉDIT AGRICOLE BR S.A');
insert into banco (numero, nome) values ('754', 'BANCO SISTEMA');
insert into banco (numero, nome) values ('098', 'CREDIALIANÇA CCR');
insert into banco (numero, nome) values ('610', 'BANCO VR S.A');
insert into banco (numero, nome) values ('712', 'BANCO OURINVEST S.A');
insert into banco (numero, nome) values ('010', 'CREDICOAMO');
insert into banco (numero, nome) values ('283', 'RB CAPITAL INVESTIMENTOS DTVM LTDA');
insert into banco (numero, nome) values ('217', 'BANCO JOHN DEERE S.A');
insert into banco (numero, nome) values ('117', 'ADVANCED CC LTDA');
insert into banco (numero, nome) values ('336', 'BANCO C6 S.A – C6 BANK');
insert into banco (numero, nome) values ('654', 'BANCO DIGIMAIS S.A');